#ifndef MEDIA_PLAYER_PROTOCOL_H
#define MEDIA_PLAYER_PROTOCOL_H

#define MEDIA_PLAYER_PROTOCOL_VERSION 1
#define MEDIA_PLAYER_CONTROL_PROTOCOL_VERSION 1
#define MEDIA_PLAYER_FILE_PREFIX "file:"
#define MEDIA_PLAYER_DVD_PREFIX "dvd:"
#define MEDIA_PLAYER_ISO_PREFIX "iso:"
#define MEDIA_PLAYER_DVD_MENU_PREFIX "dvdmenu:"
#define MEDIA_PLAYER_ISO_MENU_PREFIX "isomenu:"

/* Private SOCK_SEQPACKET channel between MiSTer Main and the ARM helper. */
#define MEDIA_PLAYER_CONTROL_PREVIOUS_CHAPTER 0x01
#define MEDIA_PLAYER_CONTROL_NEXT_CHAPTER     0x02
#define MEDIA_PLAYER_CONTROL_GO               0x03
#define MEDIA_PLAYER_CONTROL_MENU_UP          0x04
#define MEDIA_PLAYER_CONTROL_MENU_DOWN        0x05
#define MEDIA_PLAYER_CONTROL_MENU_LEFT        0x06
#define MEDIA_PLAYER_CONTROL_MENU_RIGHT       0x07
#define MEDIA_PLAYER_CONTROL_MENU_ACTIVATE    0x08
#define MEDIA_PLAYER_CONTROL_ROOT_MENU        0x09
#define MEDIA_PLAYER_CONTROL_SEEK_BACK_10      0x0a
#define MEDIA_PLAYER_CONTROL_SEEK_FORWARD_10   0x0b
#define MEDIA_PLAYER_CONTROL_SEEK_BACK_60      0x0c
#define MEDIA_PLAYER_CONTROL_SEEK_FORWARD_60   0x0d
#define MEDIA_PLAYER_CONTROL_SEEK_BACK_300     0x0e
#define MEDIA_PLAYER_CONTROL_SEEK_FORWARD_300  0x0f
#define MEDIA_PLAYER_CONTROL_READY            0x81
#define MEDIA_PLAYER_CONTROL_MENU_ENTER       0x82
#define MEDIA_PLAYER_CONTROL_MENU_LEAVE       0x83
#define MEDIA_PLAYER_CONTROL_MENU_CONTINUE    0x84
#define MEDIA_PLAYER_CONTROL_ERROR            0xff

#define MEDIA_PLAYER_PTS_MARKER_CODE 0xb0
#define MEDIA_PLAYER_PCM_MARKER_CODE 0xb1
#define MEDIA_PLAYER_PCM_END_MARKER_CODE 0xb6
#define MEDIA_PLAYER_OVERLAY_MARKER_CODE 0xb9
#define MEDIA_PLAYER_OVERLAY_CLEAR  0x00
#define MEDIA_PLAYER_OVERLAY_CONFIG 0x01
#define MEDIA_PLAYER_OVERLAY_DATA   0x02
#define MEDIA_PLAYER_OVERLAY_COMMIT 0x03
#define MEDIA_PLAYER_OVERLAY_STYLE  0x04
#define MEDIA_PLAYER_AUDIO_UI_BEGIN  0x10
#define MEDIA_PLAYER_AUDIO_UI_DATA   0x11
#define MEDIA_PLAYER_AUDIO_UI_COMMIT 0x12
#define MEDIA_PLAYER_PCM_MODE_STEREO 0x01
#define MEDIA_PLAYER_PCM_MODE_48K 0x02
#define MEDIA_PLAYER_PCM_MODE_NON_AUDIO 0x80
#define MEDIA_PLAYER_PCM_MODE_48K_STEREO \
    (MEDIA_PLAYER_PCM_MODE_48K | MEDIA_PLAYER_PCM_MODE_STEREO)

#define MEDIA_PLAYER_CAPABILITIES \
    "protocol=1 sources=file,iso,dvd,isomenu,dvdmenu " \
    "containers=m2v,mpeg-ps,mp3,wav,flac,ogg-vorbis video=h262 " \
    "audio=mp2-s16le-44100,mp2-s16le-48000," \
    "mp3-s16le-44100,mp3-s16le-48000,wav-s16le-stereo-44100,wav-s16le-stereo-48000," \
    "flac-s16le-stereo-44100,flac-s16le-stereo-48000," \
    "ogg-vorbis-s16le-stereo-44100,ogg-vorbis-s16le-stereo-48000 " \
    "transport=inband-pcm-v1,inband-dvd-overlay-v1,inband-audio-ui-v1 " \
    "controls=chapter-v1,pause-hold-v1,dvd-menu-v1,mpeg-ps-seek-v1"

#endif
