//============================================================================
// MiSTer Media Player - controlled aligned non-zero H.262 P motion observer
//
// Standards authority: core-standards.md, source_id H262.
// Relevant records:
//   H262-003 prediction samples derive from reference samples and motion vectors
//   H262-008 slice vertical position identifies the macroblock row
//   H262-009 slice-local macroblock address progression
//   H262-011 P motion-forward-only macroblock_type code 001
//   H262-014 Table B.1 macroblock_address_increment VLCs
//   H262-015 skipped P-frame macroblocks reset prediction to zero motion
//   H262-016 controlled f_code=3 motion_code +8/residual 3 reconstructs +32
//   H262-017 4:2:0 chroma vector is derived by halving the luma vector
//
// Phase 1U-k controlled boundary:
//   - sequence geometry exactly 128x96 (8x6 macroblocks);
//   - progressive frame P picture with forward f_code=(3,3);
//   - six slices, vertical positions 1..6;
//   - every row has the exact semantic pattern generated by
//     generate_test_p_aligned_motion_right.py:
//       col0 coded motion-forward-only with reconstructed vector (+32,0),
//       col1 skipped (therefore predictor reset to zero),
//       col2 coded with MBA increment 2 and vector (0,0),
//       col3..7 coded with MBA increment 1 and vector (0,0),
//       no residual coefficients.
//
// The byte comparison below is a controlled hardware proof, not a general P
// macroblock parser and not an H.262 validity restriction.
//============================================================================

module mpeg2_h262_p_aligned_motion_syntax_probe
(
    input  wire       clk,
    input  wire       reset,
    input  wire [7:0] stream_data,
    input  wire       stream_valid,

    output reg        aligned_candidate,
    output reg        aligned_seen,
    output wire       aligned_complete_now,
    output reg        probe_error
);

localparam [7:0]
    PICTURE_START_CODE   = 8'h00,
    SEQUENCE_HEADER_CODE = 8'hB3,
    EXTENSION_START_CODE = 8'hB5;

localparam [4:0] EXPECTED_SLICE_COUNT = 5'd11; // 8 payload + 000001 prefix

reg [31:0] byte_window;
wire [31:0] byte_window_next = {byte_window[23:0], stream_data};
wire        start_code_now   = (byte_window_next[31:8] == 24'h000001);
wire [7:0]  start_code_value = byte_window_next[7:0];
wire        slice_start_now  = start_code_now &&
                               (start_code_value >= 8'h01) &&
                               (start_code_value <= 8'hAF);
wire post_p_boundary_now =
    (start_code_value == PICTURE_START_CODE) ||
    (start_code_value == SEQUENCE_HEADER_CODE);

reg        sequence_capture;
reg [1:0]  sequence_count;
reg [23:0] sequence_shift;
wire [23:0] sequence_next = {sequence_shift[15:0], stream_data};
reg        geometry_128x96;

reg        picture_capture;
reg        picture_count;
reg [15:0] picture_shift;
wire [15:0] picture_next = {picture_shift[7:0], stream_data};
reg        current_picture_is_p;

reg        pce_capture;
reg [2:0]  pce_count;
reg [39:0] pce_shift;
wire [39:0] pce_next = {pce_shift[31:0], stream_data};

reg        slice_capture;
reg [3:0]  slice_row_number;
reg [4:0]  slice_count;
reg        row_payload_ok;
reg        proof_done;

reg [7:0] expected_payload_byte;
always @* begin
    case (slice_count)
        5'd0: expected_payload_byte = 8'h12;
        5'd1: expected_payload_byte = 8'h41;
        5'd2: expected_payload_byte = 8'h6E;
        5'd3: expected_payload_byte = 8'hCF;
        5'd4: expected_payload_byte = 8'h3C;
        5'd5: expected_payload_byte = 8'hF3;
        5'd6: expected_payload_byte = 8'hCF;
        5'd7: expected_payload_byte = 8'h38;
        default: expected_payload_byte = 8'h00;
    endcase
end

assign aligned_complete_now =
    stream_valid &&
    slice_capture &&
    start_code_now &&
    post_p_boundary_now &&
    (slice_row_number == 4'd6) &&
    (slice_count == EXPECTED_SLICE_COUNT) &&
    row_payload_ok;

always @(posedge clk) begin
    if (reset) begin
        byte_window          <= 32'd0;
        sequence_capture     <= 1'b0;
        sequence_count       <= 2'd0;
        sequence_shift       <= 24'd0;
        geometry_128x96      <= 1'b0;
        picture_capture      <= 1'b0;
        picture_count        <= 1'b0;
        picture_shift        <= 16'd0;
        current_picture_is_p <= 1'b0;
        pce_capture          <= 1'b0;
        pce_count            <= 3'd0;
        pce_shift            <= 40'd0;
        aligned_candidate    <= 1'b0;
        aligned_seen         <= 1'b0;
        slice_capture        <= 1'b0;
        slice_row_number     <= 4'd0;
        slice_count          <= 5'd0;
        row_payload_ok       <= 1'b0;
        proof_done           <= 1'b0;
        probe_error          <= 1'b0;
    end
    else if (stream_valid) begin
        byte_window <= byte_window_next;

        if (sequence_capture) begin
            sequence_shift <= sequence_next;
            if (sequence_count == 2'd2) begin
                sequence_capture <= 1'b0;
                sequence_count   <= 2'd0;
                geometry_128x96  <=
                    (sequence_next[23:12] == 12'd128) &&
                    (sequence_next[11:0]  == 12'd96);
            end
            else begin
                sequence_count <= sequence_count + 2'd1;
            end
        end
        else if (start_code_now &&
                 (start_code_value == SEQUENCE_HEADER_CODE)) begin
            sequence_capture <= 1'b1;
            sequence_count   <= 2'd0;
            sequence_shift   <= 24'd0;
        end

        if (picture_capture) begin
            picture_shift <= picture_next;
            if (picture_count) begin
                picture_capture      <= 1'b0;
                picture_count        <= 1'b0;
                current_picture_is_p <= (picture_next[5:3] == 3'd2);
                aligned_candidate    <= 1'b0;
            end
            else begin
                picture_count <= 1'b1;
            end
        end
        else if (start_code_now &&
                 (start_code_value == PICTURE_START_CODE)) begin
            picture_capture <= 1'b1;
            picture_count   <= 1'b0;
            picture_shift   <= 16'd0;
        end

        if (pce_capture) begin
            pce_shift <= pce_next;
            if (pce_count == 3'd4) begin
                pce_capture <= 1'b0;
                pce_count   <= 3'd0;
                aligned_candidate <=
                    geometry_128x96 &&
                    current_picture_is_p &&
                    (pce_next[39:36] == 4'h8) &&
                    (pce_next[35:32] == 4'd3) &&
                    (pce_next[31:28] == 4'd3) &&
                    (pce_next[17:16] == 2'b11) &&
                    (pce_next[14]    == 1'b1) &&
                    (pce_next[13]    == 1'b0) &&
                    (pce_next[12]    == 1'b0) &&
                    (pce_next[10]    == 1'b0);
            end
            else begin
                pce_count <= pce_count + 3'd1;
            end
        end
        else if (current_picture_is_p && start_code_now &&
                 (start_code_value == EXTENSION_START_CODE)) begin
            pce_capture <= 1'b1;
            pce_count   <= 3'd0;
            pce_shift   <= 40'd0;
        end

        if (!proof_done && slice_capture) begin
            if (start_code_now) begin
                if ((slice_count != EXPECTED_SLICE_COUNT) ||
                    !row_payload_ok) begin
                    slice_capture <= 1'b0;
                    proof_done    <= 1'b1;
                    probe_error   <= 1'b1;
                end
                else if (slice_row_number < 4'd6) begin
                    if (start_code_value == {4'd0, slice_row_number} + 8'd1) begin
                        slice_row_number <= slice_row_number + 4'd1;
                        slice_count      <= 5'd0;
                        row_payload_ok   <= 1'b1;
                    end
                    else begin
                        slice_capture <= 1'b0;
                        proof_done    <= 1'b1;
                        probe_error   <= 1'b1;
                    end
                end
                else begin
                    slice_capture <= 1'b0;
                    proof_done    <= 1'b1;
                    if (post_p_boundary_now)
                        aligned_seen <= 1'b1;
                    else
                        probe_error <= 1'b1;
                end
            end
            else begin
                if ((slice_count < 5'd8) &&
                    (stream_data != expected_payload_byte))
                    row_payload_ok <= 1'b0;
                if (slice_count != 5'h1F)
                    slice_count <= slice_count + 5'd1;
            end
        end
        else if (!proof_done && aligned_candidate && slice_start_now) begin
            if (start_code_value == 8'h01) begin
                slice_capture    <= 1'b1;
                slice_row_number <= 4'd1;
                slice_count      <= 5'd0;
                row_payload_ok   <= 1'b1;
            end
            else begin
                proof_done  <= 1'b1;
                probe_error <= 1'b1;
            end
        end
    end
end

endmodule
