#!/usr/bin/env python3
"""Generate stock Main direct subtitle actions and their shared RTL mapping."""
import argparse
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
root=Path(__file__).resolve().parents[1]
offsets=[0]+[v for v in range(-50,51,2) if v!=0]
speeds=[100]+[v for v in range(50,151,2) if v!=100]
items=['P1,Subtitles;','P1S1,SRT,Load;','P1O[120],Visible,Yes,No;',
       'P1P2,Offset;','P1P3,Speed;']
rtl='// Generated by tools/make_subtitle_menu.py. One stock Main T pulse selects a value.\n'
for page,values,start,kind in [(2,offsets,7,'offset'),(3,speeds,58,'speed')]:
 for i,v in enumerate(values):
  label=('0.0 s (default)' if v==0 else f'{v/10:+.1f} s') if kind=='offset' else ('1.00x (default)' if v==100 else f'{v/100:.2f}x')
  items.append(f'P{page}T[{start+i}],{label};')
  code=(v if v>=0 else v+101) if kind=='offset' else (v-100 if v>=100 else v+1)
  rtl+=f"if ({kind}_select[{i}]) {kind}_code <= 7'd{code};\n"
 items.append(f'P{page}P1,Subtitles;')
 # 51 actions + explicit Subtitles link + Main Back = 53 selectable rows.
 assert len(values)+2<64
# Disable every subtitle row in audio mode, including Main's flattened view.
items=['D0'+item for item in items]
assert len(set(offsets))==len(set(speeds))==51
assert all(len(x)<2048 for x in items)
assert sum(map(len,items))<9000
outputs={'MediaPlayer_subtitle_menu.svh':'// Generated by tools/make_subtitle_menu.py; included inside CONF_STR.\n'+''.join('\t"'+x+'",\n' for x in items),
         'rtl/media_subtitle_select_map.svh':rtl}
for f,text in outputs.items():
 path=root/f
 if a.check:assert path.read_text()==text, 'regenerate '+f
 else:path.write_text(text)
print(f'SUBTITLE_MENU_PASS offset={len(offsets)} speed={len(speeds)} selectable_per_page=53 bytes={sum(map(len,items))}')
