#!/usr/bin/env python3
"""Generate stock-Main subtitle options, with neutral settings at status zero."""
import argparse
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--check',action='store_true');a=p.parse_args()
root=Path(__file__).resolve().parents[1]
# Circular option order gives the neutral setting index zero; left/right still
# decrease/increase by one step, with Main's normal wrap at the endpoints.
offsets=list(range(0,51))+list(range(-50,0))
speeds=list(range(100,151))+list(range(50,100))
items=['P1,Subtitles;','P1S1,SRT,Load;','P1O[120],Visible,Yes,No;',
 'P1O[119:113],Offset,'+','.join(('0.0 s' if v==0 else f'{v/10:+.1f} s') for v in offsets)+';',
 'P1O[112:106],Speed,'+','.join(f'{v/100:.2f}x' for v in speeds)+';']
assert all(len(x)<2048 for x in items), 'stock Main per-item buffer'
text='// Generated by tools/make_subtitle_menu.py; included inside CONF_STR.\n'
for item in items:text+='\t"'+item+'",\n'
p=root/'MediaPlayer_subtitle_menu.svh'
if a.check:
 assert p.read_text()==text, 'regenerate subtitle menu'
else:p.write_text(text)
print(f'SUBTITLE_MENU_PASS offset={len(offsets)} speed={len(speeds)} bytes={sum(map(len,items))}')
